language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install .
# command to run tests
script: pytest -v --cov=rftg --cov-report html --cov-report xml  tests/