[build-system]
requires = [ "setuptools >= 35.0.2", "wheel >= 0.29.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "rftg"
version = "0.1.0"
description = "Race for the galaxy"
authors = ["Damien Carol <damien.carol@gmail.com>"]